In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

In [3]:
print(a1)

[1 2 3]


In [5]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [8]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [9]:
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
c = np.arrange(15)

AttributeError: module 'numpy' has no attribute 'arrange'